return {
	Coins = 0,
	XP = 0,
	Level = 1,
	MaxFloorReached = 0,
	UnlockedCheckpoints = {},
	OpenedMineChests = {},
	Inventory = {},
	EquippedPickaxe = "Wood Pickaxe",
	EquippedWeapon = "Wood Sword",
	EquippedHelmet = "",
	EquippedChestplate = "",
	EquippedLeggings = "",
	EquippedBoots = "",
	HotbarVersion = 0,
	HotbarSlots = {
		{name = "1", value = ""},
		{name = "2", value = ""},
		{name = "3", value = ""},
		{name = "4", value = ""},
		{name = "5", value = ""},
	},
	SelectedHotbarSlot = 0,
	UnlockedRecipes = {},
	TutorialStates = {{name = "Intro", value = false}},
}
