return {
	Coins = 0,
	XP = 0,
	Level = 1,
	MaxFloorReached = 0,
	UnlockedCheckpoints = {},
	Inventory = {},
	EquippedPickaxe = "Wood Pickaxe",
	EquippedWeapon = "Wood Sword",
	EquippedHelmet = "",
	EquippedChestplate = "",
	EquippedBoots = "",
	UnlockedRecipes = {},
	TutorialStates = {{name = "Intro", value = false}},
}
