local config = {
	DEFAULT_WALKSPEED = 16,
	DEFAULT_MAXHEALTH = 100,
	DEFAULT_XP_REWARD = 15,
	MINE_SWING_COOLDOWN = 0.4,
	ATTACK_SWING_COOLDOWN = 0.5,
	ORE_NODE_RESPAWN_TIME = 15,
	INVULNERABILITY_WINDOW = 0.5,
	MINE_REACH_DISTANCE = 12,
	ATTACK_REACH_DISTANCE = 8,
	CONVERSABLE_ENTITY_MAX_DISTANCE = 15,
	SERVER_ACTION_LENIENCY = 0.1,
}

return config
