local EnemyConfig = {
	["Cave Slime"] = {
		layer = 1,
		hp = 15,
		damage = 3,
		defense = 0,
		behavior = "wander",
		movementBehavior = "SlimeLeap",
		attackBehavior = "SlimeLunge",
		walkSpeed = 6,
		detectionRadius = 20,
		attackRange = 8,
		drops = {
			{ name = "Slime Gel", chance = 0.5 },
			{ name = "Coins", minAmount = 2, maxAmount = 5 },
		},
		xpReward = 10,
	},
	["Cave Bat"] = {
		layer = 1,
		hp = 10,
		damage = 8,
		defense = 0,
		behavior = "wander",
		movementBehavior = "FlyingHover",
		attackBehavior = "DefaultMelee",
		walkSpeed = 10,
		detectionRadius = 25,
		attackRange = 3,
		drops = {
			{ name = "Bat Wing", chance = 0.5 },
			{ name = "Coins", minAmount = 2, maxAmount = 5 },
		},
		xpReward = 10,
	},
	["Goblin"] = {
		layer = 2,
		hp = 30,
		damage = 12,
		defense = 3,
		behavior = "patrol",
		movementBehavior = "DefaultGround",
		attackBehavior = "DefaultMelee",
		walkSpeed = 8,
		detectionRadius = 25,
		attackRange = 5,
		drops = {
			{ name = "Coins", minAmount = 5, maxAmount = 10 },
			{ name = "Iron", chance = 0.3 },
		},
		xpReward = 20,
	},
	["Shadow Bat"] = {
		layer = 2,
		hp = 20,
		damage = 15,
		defense = 2,
		behavior = "wander",
		movementBehavior = "FlyingHover",
		attackBehavior = "DefaultMelee",
		walkSpeed = 14,
		detectionRadius = 20,
		attackRange = 3,
		drops = {
			{ name = "Bat Wing", chance = 0.6 },
			{ name = "Coins", minAmount = 5, maxAmount = 8 },
		},
		xpReward = 20,
	},
	["Skeleton"] = {
		layer = 3,
		hp = 50,
		damage = 18,
		defense = 5,
		behavior = "patrol",
		movementBehavior = "DefaultGround",
		attackBehavior = "DefaultMelee",
		walkSpeed = 7,
		detectionRadius = 30,
		attackRange = 6,
		drops = {
			{ name = "Bone Fragment", chance = 0.6 },
			{ name = "Coins", minAmount = 8, maxAmount = 12 },
		},
		xpReward = 30,
	},
	["Rock Golem"] = {
		layer = 3,
		hp = 80,
		damage = 15,
		defense = 12,
		behavior = "wander",
		movementBehavior = "DefaultGround",
		attackBehavior = "DefaultMelee",
		walkSpeed = 4,
		detectionRadius = 15,
		attackRange = 5,
		drops = {
			{ name = "Stone", chance = 0.8 },
			{ name = "Gold", chance = 0.3 },
			{ name = "Coins", minAmount = 8, maxAmount = 15 },
		},
		xpReward = 35,
	},
	["Gold Guardian"] = {
		layer = 4,
		hp = 100,
		damage = 25,
		defense = 10,
		behavior = "patrol",
		movementBehavior = "DefaultGround",
		attackBehavior = "DefaultMelee",
		walkSpeed = 7,
		detectionRadius = 25,
		attackRange = 5,
		drops = {
			{ name = "Gold", chance = 0.6 },
			{ name = "Coins", minAmount = 10, maxAmount = 15 },
		},
		xpReward = 40,
	},
	["Crystal Spider"] = {
		layer = 4,
		hp = 60,
		damage = 30,
		defense = 5,
		behavior = "wander",
		movementBehavior = "DefaultGround",
		attackBehavior = "DefaultMelee",
		walkSpeed = 14,
		detectionRadius = 20,
		attackRange = 4,
		drops = {
			{ name = "Diamond", chance = 0.2 },
			{ name = "Coins", minAmount = 10, maxAmount = 15 },
		},
		xpReward = 40,
	},
	["Lava Slime"] = {
		layer = 5,
		hp = 90,
		damage = 28,
		defense = 8,
		behavior = "wander",
		movementBehavior = "SlimeLeap",
		attackBehavior = "SlimeLunge",
		walkSpeed = 6,
		detectionRadius = 20,
		attackRange = 8,
		drops = {
			{ name = "Slime Gel", chance = 0.6 },
			{ name = "Obsidian", chance = 0.3 },
			{ name = "Coins", minAmount = 12, maxAmount = 15 },
		},
		xpReward = 45,
	},
	["Obsidian Knight"] = {
		layer = 5,
		hp = 150,
		damage = 35,
		defense = 20,
		behavior = "patrol",
		movementBehavior = "DefaultGround",
		attackBehavior = "DefaultMelee",
		walkSpeed = 6,
		detectionRadius = 25,
		attackRange = 5,
		drops = {
			{ name = "Obsidian", chance = 0.5 },
			{ name = "Coins", minAmount = 12, maxAmount = 15 },
		},
		xpReward = 50,
	},
	["Fire Elemental"] = {
		layer = 6,
		hp = 120,
		damage = 40,
		defense = 10,
		behavior = "patrol",
		movementBehavior = "DefaultGround",
		attackBehavior = "DefaultMelee",
		walkSpeed = 8,
		detectionRadius = 30,
		attackRange = 8,
		drops = {
			{ name = "Fire Essence", chance = 0.5 },
			{ name = "Coins", minAmount = 15, maxAmount = 15 },
		},
		xpReward = 50,
	},
	["Magma Wyrm"] = {
		layer = 6,
		hp = 200,
		damage = 45,
		defense = 15,
		behavior = "wander",
		movementBehavior = "DefaultGround",
		attackBehavior = "DefaultMelee",
		walkSpeed = 10,
		detectionRadius = 20,
		attackRange = 6,
		drops = {
			{ name = "Fire Essence", chance = 0.6 },
			{ name = "Mythril", chance = 0.3 },
			{ name = "Coins", minAmount = 15, maxAmount = 15 },
		},
		xpReward = 50,
	},
}

return EnemyConfig
